### ISSUE TITLE
Volta GPUs not supported

### ISSUE THREAD

**Issue by nphtan** [UniHD-CEG/gpugraph500#1]
I have been trying to run this on a Power9+V100 cluster and have ran into issues with building the code. The problem is that on Volta the L1 and shared memory are configurable similar to Kepler. By default it tries to use 96KB of shared memory but Cuda by default dedicates 48KB to shared memory. I have tried setting the cache configuration in main.cpp but haven't had any luck. Any suggestions or fixes would be appreciated. Here is the exact error.

/usr/local/cuda/bin/nvcc --ptxas-options="-O3" -arch=sm_70  -ftz=true -prec-div=false -prec-sqrt=false -fmad=true -c -ccbin /home/ntan1/ComputationalUncertaintyHPC/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-7.3.0-i2zksl2ugszs6k4neftiz6keilpuduxg/bin/g++ -std=c++11 -Xcompiler ,-m64,-O3,-pipe, -DINSTRUMENTED,  -D_COMPRESSION,   -D_CUDA, -I/home/ntan1/ComputationalUncertaintyHPC/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.3.0/openmpi-4.0.1-3wlmtktvg442zsglw5phyjh2xpezfl7y/include --compiler-options -fno-strict-aliasing -O3 -use_fast_math  -m64 -I/usr/local/cuda/include -I.. cuda/cuda_bfs.cu -o cuda_bfs_cuda.o
ptxas error   : Entry function '_ZN4b40c5graph3bfs18partition_contract7upsweep6KernelINS3_12KernelPolicyINS_9partition7upsweep12TuningPolicyINS1_11ProblemTypeIljhhLb1EEELi350ELb0ELi4ELi9ELi8ELi7ELi0ELi2ELNS_4util2io2ld13CacheModifierE0ELNSC_2st13CacheModifierE0EEELb1EEEEEvNT_8VertexIdEiPSK_PNSJ_9ValidFlagEPNSJ_5SizeTEPNSJ_11VisitedMaskENSB_15CtaWorkProgressISO_EESO_NSB_18KernelRuntimeStatsE' uses too much shared data (0x17f80 bytes, 0xc000 max)
make: *** [cuda_bfs_cuda.o] Error 255

**Comment by rom3r4** [comment]
Since Volta is compute capability 7, maybe this works https://stackoverflow.com/questions/23648525/cuda-ptxas-error-function-uses-too-much-shared-data? 

Maybe you could try adjusting the `nvcc` compilation parameters in `gpugraph500/cpu_2d/Makefile.am`?

could you try perhaps one of these:
  -gencode=arch=compute_50,code=sm_50
  -gencode=arch=compute_52,code=sm_52
  -gencode=arch=compute_60,code=sm_60
  -gencode=arch=compute_61,code=sm_61
  -gencode=arch=compute_61,code=compute_61

https://docs.nvidia.com/cuda/volta-compatibility-guide/index.html
